# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "remix-chat"
client_id = "a4765dd536351f4203f83c7dea06f809"
application_url = "https://cities-minute-routers-officially.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://cities-minute-routers-officially.trycloudflare.com/auth/callback",
  "https://cities-minute-routers-officially.trycloudflare.com/auth/shopify/callback",
  "https://cities-minute-routers-officially.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "lewkdev.myshopify.com"
